version: "3.7"
services:
  penv:
    build: .
    tty: true
    hostname: penv
    volumes:
      -  "/var/run/docker.sock:/var/run/docker.sock"
      -  "~/workspaces:/opt/workspaces"

    ports:
      - "22"
    restart: unless-stopped
    networks:
        - penv-network
    secrets:
        - host_ssh_key

volumes:
  volume-name:
    driver: local

networks:
    penv-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.30.80.0/24

secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa
